### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by KarlZeilhofer** [remyar/Kicad_Tools#1]
Hi, 
I tried to clone your repo and just start the index.html. But there only some spinner icon shows up in the middle of the page, but then nothing happens. 
Greets, Karl

**Comment by remyar** [comment]
hi carl , the best way is to use the setup to install the tool !!!

after , you have a icon on desktop and run it !!!

https://github.com/remyar/Kicad_Tools/releases/download/0.0.2/Kicad_Tools.Setup.0.0.2.exe

**Comment by remyar** [comment]
in other case, you can run the code on every machine ( Linux / OSX / Windows ) if you have nodeJS  6+ installed!

Installation : 
1: clone the repository
2: enter in the repository directory
3: open console or CMD
4: execute "npm install"
5: execute "npm run webpack"

the tools is ok and installed

**### Standalone Use :**
1: open console/CMD in directory
2 : execute "npm start"

OR

1: open console/CMD in directory
2: execute "npm run dist"
3: open dist folder
4: install "kicadTools Setup.exe"
5: launch "KicadTools"
OR
4: open "win-unpacked"
5: launch "KicadTools.exe"

**Comment by KarlZeilhofer** [comment]
On Linux Mint 19 I get these warnings for `npm install`:  
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none was installed.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none was installed.
npm WARN vuex-modal@0.2.1 requires a peer of vuex@^2.0.0 but none was installed.
npm WARN Kicad_Tools@0.0.2 No repository field.
npm WARN Kicad_Tools@0.0.2 No license field.
```

EDIT: but It did start anyway. 

@remyar: the build instructions should be put into the README.md, also the usage and purpose of that project.

**Comment by remyar** [comment]
hi Karl ,

yes, i think to modify the readme for install it on all OS.

it's just a warn but work fine normaly !!

i've worked on full traslation in EN, if you want, i release it now !
